spring:
    application:
        name: db-service
server:
   port: 8300

# security:
#   basic:
#     enabled: false
# management:
#   security:
#     enabled: false



#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

